In [1]:
# libraries
import numpy as np
import pandas as pd

In [2]:
data  =pd.Series([0.25,0.50,0.35,0.40])
data

0    0.25
1    0.50
2    0.35
3    0.40
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.35, 0.4 ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:2]

1    0.5
dtype: float64

In [7]:
data[1:3]

1    0.50
2    0.35
dtype: float64

In [8]:
data[:3]

0    0.25
1    0.50
2    0.35
dtype: float64

In [9]:
data = pd.Series([0.25,0.35,0.45,0.52],index = ["a","b","c","d"])

In [10]:
data

a    0.25
b    0.35
c    0.45
d    0.52
dtype: float64

In [11]:
data["b"]

0.35

### Dictionary

In [12]:
population_dict = {"California": 38332521,
                  "Texas":26448193,
                  "New York":19651127,
                  "Florida":19552860,
                  "Illinois":12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
population["California":"Illinois"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Constructing Series objects

In [14]:
pd.Series(5, index=[100,2000,3000])

100     5
2000    5
3000    5
dtype: int64

In [15]:
pd.Series({2:"a",1:"b",3:"c"})

2    a
1    b
3    c
dtype: object

## The Pandas DataFrame Object
### DataFrame as Generalized Numpy Array

In [16]:
area_dict = {'California': 423967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312,
             'Illinois': 149995}

area = pd.Series(area_dict)

area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [17]:
states = pd.DataFrame({"population": population,
                      "area":area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [18]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [19]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as Specialized Dictionary

In [20]:
states["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [21]:
states["population"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### Constructing DataFrame Objects

In [22]:
pd.DataFrame(population, columns=["Population"])

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [23]:
data = [{"a":i,"b":2*i}
       for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [24]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [25]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### From a Numpy Structured Array

In [26]:
A = np.zeros(3,dtype=[("A","i8"),("B","f8")])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [27]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

# The Pandas Index Object

In [28]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as immutable array

In [29]:
ind[1]

3

In [30]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [31]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


#### Index as ordered set

In [32]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [33]:
indA & indB #intersection

C:\Users\User\AppData\Local\Temp\ipykernel_1868\1860335538.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB #intersection


Int64Index([3, 5, 7], dtype='int64')

In [34]:
indA | indB #union

C:\Users\User\AppData\Local\Temp\ipykernel_1868\2837849747.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB #union


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [35]:
indA ^indB #symetric difference

C:\Users\User\AppData\Local\Temp\ipykernel_1868\2834346342.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^indB #symetric difference


Int64Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection
### Data Selection in Series

In [38]:
data = pd.Series([0.25,0.5,0.75,1.0],
                index=["a","b","c","d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
data["b"]

0.5

In [40]:
"a" in data

True

In [41]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [42]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [43]:
data["e"] = 1.25

In [44]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one dimensional array

In [45]:
#slicing by explicit index
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
#slicing by implicit index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [48]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [49]:
# fancy indexing
data[["a","e"]]

a    0.25
e    1.25
dtype: float64

### Indexers: loc,iloc, and ix

In [50]:
data = pd.Series(["a","b","c"], index=[1,3,5])

In [51]:
data

1    a
3    b
5    c
dtype: object

In [52]:
# explicit index when indexing
data[1]

'a'

In [56]:
data

1    a
3    b
5    c
dtype: object

In [53]:
data.loc[1:3]

1    a
3    b
dtype: object

In [54]:
data.iloc[1]

'b'

In [55]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame
#### Dataframe as a Dictionary

In [57]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [58]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [59]:
data.area


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [60]:
data.area is data["area"]

True

In [61]:
data.pop is data ["pop"]

False

In [62]:
data["density"] = data["pop"] / data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [66]:
### DataFrame as Two-Dimensional Array
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [67]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [65]:
data.T # transpose

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [68]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [69]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [70]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [71]:
data.loc[:"Illinois",:"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [75]:
data.loc[data.density > 100,["pop","density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [76]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Additional Indexing Conventions

In [77]:
data["Florida":"Illinois"]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [78]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [79]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121